In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('astrotrain.csv')

C:\Users\siddh\AppData\Local\Temp\ipykernel_5880\1523602027.py:1: DtypeWarning: Columns (80) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('astrotrain.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40003 entries, 0 to 40002
Data columns (total 84 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SUBSURVEY             40000 non-null  object
 1   SNID                  40001 non-null  float64
 2   IAUC                  40000 non-null  object
 3   FAKE                  40000 non-null  float64
 4   RA                    40000 non-null  float64
 5   DECL                  40000 non-null  float64
 6   PIXSIZE               40000 non-null  float64
 7   NXPIX                 40000 non-null  float64
 8   NYPIX                 40000 non-null  float64
 9   CCDNUM                40000 non-null  float64
 10  SNTYPE                40000 non-null  float64
 11  NOBS                  40000 non-null  float64
 12  PTROBS_MIN            40000 non-null  float64
 13  PTROBS_MAX            40000 non-null  float64
 14  MWEBV                 40000 non-null  float64
 15  MWEBV_ERR             40000 non-null  float64
 16  REDSHIFT_HELIO        40000 non-null  float64
 17  REDSHIFT_HELIO_ERR    40000 non-null  float64
 18  REDSHIFT_FINAL        40000 non-null  float64
 19  REDSHIFT_FINAL_ERR    40000 non-null  float64
 20  VPEC                  40000 non-null  float64
 21  VPEC_ERR              40000 non-null  float64
 22  HOSTGAL_OBJID         40000 non-null  float64
 23  HOSTGAL_PHOTOZ        40000 non-null  float64
 24  HOSTGAL_PHOTOZ_ERR    40000 non-null  float64
 25  Unnamed: 25           40000 non-null  float64
 26  HOSTGAL_SPECZ_ERR     39999 non-null  float64
 27  HOSTGAL_SNSEP         40000 non-null  float64
 28  HOSTGAL_LOGMASS       40000 non-null  float64
 29  HOSTGAL_LOGMASS_ERR   40000 non-null  float64
 30  HOSTGAL_MAG_g         40000 non-null  float64
 31  HOSTGAL_MAG_r         40000 non-null  float64
 32  HOSTGAL_MAG_i         40000 non-null  float64
 33  HOSTGAL_MAG_z         40000 non-null  float64
 34  HOSTGAL_SB_FLUXCAL_g  40000 non-null  float64
 35  HOSTGAL_SB_FLUXCAL_r  40000 non-null  float64
 36  HOSTGAL_SB_FLUXCAL_i  40000 non-null  float64
 37  HOSTGAL_SB_FLUXCAL_z  40000 non-null  float64
 38  PEAKMJD               40000 non-null  float64
 39  SEARCH_TYPE           40000 non-null  float64
 40  SIM_MODEL_NAME        40000 non-null  object
 41  SIM_MODEL_INDEX       40000 non-null  float64
 42  SIM_TYPE_INDEX        40000 non-null  float64
 43  SIM_TYPE_NAME         40000 non-null  object
 44  SIM_NON1a             40000 non-null  float64
 45  SIM_LIBID             40000 non-null  float64
 46  SIM_NGEN_LIBID        40000 non-null  float64
 47  SIM_NOBS_UNDEF        40000 non-null  float64
 48  SIM_SEARCHEFF_MASK    40000 non-null  float64
 49  SIM_REDSHIFT_HELIO    40000 non-null  float64
 50  SIM_REDSHIFT_CMB      40000 non-null  float64
 51  SIM_REDSHIFT_HOST     40000 non-null  float64
 52  SIM_VPEC              40000 non-null  float64
 53  SIM_HOSTLIB(Mi_abs)   40000 non-null  float64
 54  SIM_DLMU              40000 non-null  float64
 55  SIM_LENSDMU           40000 non-null  float64
 56  SIM_RA                40000 non-null  float64
 57  SIM_DECL              40000 non-null  float64
 58  SIM_MWEBV             40000 non-null  float64
 59  SIM_PEAKMJD           40000 non-null  float64
 60  SIM_MAGSMEAR_COH      40000 non-null  float64
 61  SIM_AV                40000 non-null  float64
 62  SIM_RV                40000 non-null  float64
 63  SIM_SALT2x0           18251 non-null  float64
 64  SIM_SALT2x1           18251 non-null  float64
 65  SIM_SALT2c            18251 non-null  float64
 66  SIM_SALT2mB           18251 non-null  float64
 67  SIM_SALT2alpha        18251 non-null  float64
 68  SIM_SALT2beta         18251 non-null  float64
 69  SIM_PEAKMAG_g         40000 non-null  float64
 70  SIM_PEAKMAG_r         40000 non-null  float64
 71  SIM_PEAKMAG_i         40000 non-null  float64
 72  SIM_PEAKMAG_z         40000 non-null  float64
 73  SIM_EXPOSURE_g        40000 non-null  float64
 74  SIM_EXPOSURE_r        40000 non-null  float64
 75  SIM_EXPOSURE_i        40000 non-null  float64
 76  SIM_EXPOSURE_z        40000 non-null  float64
 77  SIM_GALFRAC_g         40000 non-null  float64
 78  SIM_GALFRAC_r         40000 non-null  float64
 79  SIM_GALFRAC_i         40000 non-null  float64
 80  SIM_GALFRAC_z         40000 non-null  object
 81  SIM_SUBSAMPLE_INDEX   40000 non-null  float64
 82  Unnamed: 82           0 non-null      float64
 83  d                     0 non-null      float64
dtypes: float64(79), object(5)
memory usage: 25.6+ MB

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40003 entries, 0 to 40002
Data columns (total 84 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SUBSURVEY             40000 non-null  object
 1   SNID                  40001 non-null  float64
 2   IAUC                  40000 non-null  object
 3   FAKE                  40000 non-null  float64
 4   RA                    40000 non-null  float64
 5   DECL                  40000 non-null  float64
 6   PIXSIZE               40000 non-null  float64
 7   NXPIX                 40000 non-null  float64
 8   NYPIX                 40000 non-null  float64
 9   CCDNUM                40000 non-null  float64
 10  SNTYPE                40000 non-null  float64
 11  NOBS                  40000 non-null  float64
 12  PTROBS_MIN            40000 non-null  float64
 13  PTROBS_MAX            40000 non-null  float64
 14  MWEBV                 40000 non-null  float64
 15  MWEBV_ERR             40000 non-null  float64
 16  REDSHIFT_HELIO        40000 non-null  float64
 17  REDSHIFT_HELIO_ERR    40000 non-null  float64
 18  REDSHIFT_FINAL        40000 non-null  float64
 19  REDSHIFT_FINAL_ERR    40000 non-null  float64
 20  VPEC                  40000 non-null  float64
 21  VPEC_ERR              40000 non-null  float64
 22  HOSTGAL_OBJID         40000 non-null  float64
 23  HOSTGAL_PHOTOZ        40000 non-null  float64
 24  HOSTGAL_PHOTOZ_ERR    40000 non-null  float64
 25  Unnamed: 25           40000 non-null  float64
 26  HOSTGAL_SPECZ_ERR     39999 non-null  float64
 27  HOSTGAL_SNSEP         40000 non-null  float64
 28  HOSTGAL_LOGMASS       40000 non-null  float64
 29  HOSTGAL_LOGMASS_ERR   40000 non-null  float64
 30  HOSTGAL_MAG_g         40000 non-null  float64
 31  HOSTGAL_MAG_r         40000 non-null  float64
 32  HOSTGAL_MAG_i         40000 non-null  float64
 33  HOSTGAL_MAG_z         40000 non-null  float64
 34  HOSTGAL_SB_FLUXCAL_g  40000 non-null  float64
 35  HOSTGAL_SB_FLUXCAL_r  40000 non-null  float64
 36  HOSTGAL_SB_FLUXCAL_i  40000 non-null  float64
 37  HOSTGAL_SB_FLUXCAL_z  40000 non-null  float64
 38  PEAKMJD               40000 non-null  float64
 39  SEARCH_TYPE           40000 non-null  float64
 40  SIM_MODEL_NAME        40000 non-null  object
 41  SIM_MODEL_INDEX       40000 non-null  float64
 42  SIM_TYPE_INDEX        40000 non-null  float64
 43  SIM_TYPE_NAME         40000 non-null  object
 44  SIM_NON1a             40000 non-null  float64
 45  SIM_LIBID             40000 non-null  float64
 46  SIM_NGEN_LIBID        40000 non-null  float64
 47  SIM_NOBS_UNDEF        40000 non-null  float64
 48  SIM_SEARCHEFF_MASK    40000 non-null  float64
 49  SIM_REDSHIFT_HELIO    40000 non-null  float64
 50  SIM_REDSHIFT_CMB      40000 non-null  float64
 51  SIM_REDSHIFT_HOST     40000 non-null  float64
 52  SIM_VPEC              40000 non-null  float64
 53  SIM_HOSTLIB(Mi_abs)   40000 non-null  float64
 54  SIM_DLMU              40000 non-null  float64
 55  SIM_LENSDMU           40000 non-null  float64
 56  SIM_RA                40000 non-null  float64
 57  SIM_DECL              40000 non-null  float64
 58  SIM_MWEBV             40000 non-null  float64
 59  SIM_PEAKMJD           40000 non-null  float64
 60  SIM_MAGSMEAR_COH      40000 non-null  float64
 61  SIM_AV                40000 non-null  float64
 62  SIM_RV                40000 non-null  float64
 63  SIM_SALT2x0           18251 non-null  float64
 64  SIM_SALT2x1           18251 non-null  float64
 65  SIM_SALT2c            18251 non-null  float64
 66  SIM_SALT2mB           18251 non-null  float64
 67  SIM_SALT2alpha        18251 non-null  float64
 68  SIM_SALT2beta         18251 non-null  float64
 69  SIM_PEAKMAG_g         40000 non-null  float64
 70  SIM_PEAKMAG_r         40000 non-null  float64
 71  SIM_PEAKMAG_i         40000 non-null  float64
 72  SIM_PEAKMAG_z         40000 non-null  float64
 73  SIM_EXPOSURE_g        40000 non-null  float64
 74  SIM_EXPOSURE_r        40000 non-null  float64
 75  SIM_EXPOSURE_i        40000 non-null  float64
 76  SIM_EXPOSURE_z        40000 non-null  float64
 77  SIM_GALFRAC_g         40000 non-null  float64
 78  SIM_GALFRAC_r         40000 non-null  float64
 79  SIM_GALFRAC_i         40000 non-null  float64
 80  SIM_GALFRAC_z         40000 non-null  object
 81  SIM_SUBSAMPLE_INDEX   40000 non-null  float64
 82  Unnamed: 82           0 non-null      float64
 83  d                     0 non-null      float64
dtypes: float64(79), object(5)
memory usage: 25.6+ MB

In [5]:
df.describe()

,SNID,FAKE,RA,DECL,PIXSIZE,NXPIX,NYPIX,CCDNUM,SNTYPE,NOBS,...,SIM_EXPOSURE_g,SIM_EXPOSURE_r,SIM_EXPOSURE_i,SIM_EXPOSURE_z,SIM_GALFRAC_g,SIM_GALFRAC_r,SIM_GALFRAC_i,SIM_SUBSAMPLE_INDEX,Unnamed: 82,d
count,4.000100e+04,40000.0,40000.000000,40000.000000,4.000000e+04,40000.0,40000.0,40000.00000,40000.000000,40000.000000,...,40000.0,40000.0,40000.0,40000.0,4.000000e+04,4.000000e+04,4.000000e+04,40000.0,0.0,0.0
mean,1.676763e+07,2.0,39.835341,-19.407487,2.700000e-01,-9.0,-9.0,31.58690,113.696525,59.514675,...,1.0,1.0,1.0,1.0,1.019355e+01,3.732287e+00,4.883576e+00,-9.0,NaN,NaN
std,9.683684e+06,0.0,14.800212,15.051050,2.646250e-13,0.0,0.0,17.43592,12.265149,24.185423,...,0.0,0.0,0.0,0.0,4.586269e+02,6.478933e+00,7.795332e+00,0.0,NaN,NaN
min,2.354000e+03,2.0,6.392980,-44.976723,2.700000e-01,-9.0,-9.0,1.00000,101.000000,5.000000,...,1.0,1.0,1.0,1.0,1.010000e-32,3.770000e-33,9.050000e-14,-9.0,NaN,NaN
25%,8.367381e+06,2.0,35.716156,-28.640380,2.700000e-01,-9.0,-9.0,16.00000,101.000000,42.000000,...,1.0,1.0,1.0,1.0,6.520000e-14,9.364567e-01,1.249910e+00,-9.0,NaN,NaN
50%,1.686442e+07,2.0,41.157764,-27.204088,2.700000e-01,-9.0,-9.0,32.00000,120.000000,60.000000,...,1.0,1.0,1.0,1.0,5.749799e-01,1.987298e+00,2.595640e+00,-9.0,NaN,NaN
75%,2.510417e+07,2.0,52.866702,-4.633564,2.700000e-01,-9.0,-9.0,47.00000,122.000000,73.000000,...,1.0,1.0,1.0,1.0,2.064853e+00,4.234644e+00,5.399975e+00,-9.0,NaN,NaN
max,3.359532e+07,2.0,55.512060,0.978050,2.700000e-01,-9.0,-9.0,62.00000,133.000000,223.000000,...,1.0,1.0,1.0,1.0,6.577444e+04,5.800674e+02,2.593467e+02,-9.0,NaN,NaN

In [6]:
!pip install ydata-profiling

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ydata-profiling in c:\users\siddh\appdata\roaming\python\python312\site-packages (4.12.1)
Requirement already satisfied: scipy<1.14,>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<3.10,>=3.5 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (3.8.4)
Requirement already satisfied: pydantic>=2 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (2.5.3)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (3.1.4)
Requirement already satisfied: visions<0.7.7,>=0.7.5 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (0.7.6)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (2.32.2)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (4.66.4)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (0.14.2)
Requirement already satisfied: typeguard<5,>=3 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (4.4.1)
Requirement already satisfied: imagehash==4.3.1 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from ydata-profiling) (1.8.1)
Requirement already satisfied: numba<1,>=0.56.0 in c:\programdata\anaconda3\lib\site-packages (from ydata-profiling) (0.59.1)
Requirement already satisfied: PyWavelets in c:\programdata\anaconda3\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (1.5.0)
Requirement already satisfied: pillow in c:\programdata\anaconda3\lib\site-packages (from imagehash==4.3.1->ydata-profiling) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib<3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in c:\programdata\anaconda3\lib\site-packages (from numba<1,>=0.56.0->ydata-profiling) (0.42.0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\siddh\appdata\roaming\python\python312\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.4.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2->ydata-profiling) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2->ydata-profiling) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.8.30)
Requirement already satisfied: patsy>=0.5.6 in c:\programdata\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\siddh\appdata\roaming\python\python312\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\programdata\anaconda3\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\programdata\anaconda3\lib\site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling) (3.2.1)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata-profiling) (1.16.0)

In [7]:
from ydata_profiling import ProfileReport

In [8]:
#pf = ProfileReport(df)
#pf.to_file(output_file = 'output.html')

PROBLEM STATEMENT I

1.Inspect the data types and extract basic statistics:                                                                       
a.Print Range, Mean, Median, and Standard Deviation of the dataset

In [10]:
df.describe()

,SNID,FAKE,RA,DECL,PIXSIZE,NXPIX,NYPIX,CCDNUM,SNTYPE,NOBS,...,SIM_EXPOSURE_g,SIM_EXPOSURE_r,SIM_EXPOSURE_i,SIM_EXPOSURE_z,SIM_GALFRAC_g,SIM_GALFRAC_r,SIM_GALFRAC_i,SIM_SUBSAMPLE_INDEX,Unnamed: 82,d
count,4.000100e+04,40000.0,40000.000000,40000.000000,4.000000e+04,40000.0,40000.0,40000.00000,40000.000000,40000.000000,...,40000.0,40000.0,40000.0,40000.0,4.000000e+04,4.000000e+04,4.000000e+04,40000.0,0.0,0.0
mean,1.676763e+07,2.0,39.835341,-19.407487,2.700000e-01,-9.0,-9.0,31.58690,113.696525,59.514675,...,1.0,1.0,1.0,1.0,1.019355e+01,3.732287e+00,4.883576e+00,-9.0,NaN,NaN
std,9.683684e+06,0.0,14.800212,15.051050,2.646250e-13,0.0,0.0,17.43592,12.265149,24.185423,...,0.0,0.0,0.0,0.0,4.586269e+02,6.478933e+00,7.795332e+00,0.0,NaN,NaN
min,2.354000e+03,2.0,6.392980,-44.976723,2.700000e-01,-9.0,-9.0,1.00000,101.000000,5.000000,...,1.0,1.0,1.0,1.0,1.010000e-32,3.770000e-33,9.050000e-14,-9.0,NaN,NaN
25%,8.367381e+06,2.0,35.716156,-28.640380,2.700000e-01,-9.0,-9.0,16.00000,101.000000,42.000000,...,1.0,1.0,1.0,1.0,6.520000e-14,9.364567e-01,1.249910e+00,-9.0,NaN,NaN
50%,1.686442e+07,2.0,41.157764,-27.204088,2.700000e-01,-9.0,-9.0,32.00000,120.000000,60.000000,...,1.0,1.0,1.0,1.0,5.749799e-01,1.987298e+00,2.595640e+00,-9.0,NaN,NaN
75%,2.510417e+07,2.0,52.866702,-4.633564,2.700000e-01,-9.0,-9.0,47.00000,122.000000,73.000000,...,1.0,1.0,1.0,1.0,2.064853e+00,4.234644e+00,5.399975e+00,-9.0,NaN,NaN
max,3.359532e+07,2.0,55.512060,0.978050,2.700000e-01,-9.0,-9.0,62.00000,133.000000,223.000000,...,1.0,1.0,1.0,1.0,6.577444e+04,5.800674e+02,2.593467e+02,-9.0,NaN,NaN

In [11]:
def mean(sheet):
   mean = sheet.mean(numeric_only=True)
   return mean

In [12]:
 def std (sheet) :
     std = sheet.std(numeric_only=True)
     return std

In [13]:
def range (sheet):
    k1 = sheet.max(numeric_only = True)
    k2 = sheet.min(numeric_only = True)
    range ={'min':k1 , 'max':k2}
    return range

In [14]:
def median(sheet):
    median = sheet.median(numeric_only= True)
    return median

In [15]:
range(df)

{'min': SNID                   3.359532e+07
 FAKE                   2.000000e+00
 RA                     5.551206e+01
 DECL                   9.780500e-01
 PIXSIZE                2.700000e-01
                            ...
 SIM_GALFRAC_r          5.800674e+02
 SIM_GALFRAC_i          2.593467e+02
 SIM_SUBSAMPLE_INDEX   -9.000000e+00
 Unnamed: 82                     NaN
 d                               NaN
 Length: 79, dtype: float64,
 'max': SNID                   2.354000e+03
 FAKE                   2.000000e+00
 RA                     6.392980e+00
 DECL                  -4.497672e+01
 PIXSIZE                2.700000e-01
                            ...
 SIM_GALFRAC_r          3.770000e-33
 SIM_GALFRAC_i          9.050000e-14
 SIM_SUBSAMPLE_INDEX   -9.000000e+00
 Unnamed: 82                     NaN
 d                               NaN
 Length: 79, dtype: float64}

In [16]:
mean(df)

SNID                   1.676763e+07
FAKE                   2.000000e+00
RA                     3.983534e+01
DECL                  -1.940749e+01
PIXSIZE                2.700000e-01
                           ...
SIM_GALFRAC_r          3.732287e+00
SIM_GALFRAC_i          4.883576e+00
SIM_SUBSAMPLE_INDEX   -9.000000e+00
Unnamed: 82                     NaN
d                               NaN
Length: 79, dtype: float64

In [17]:
median(df)

SNID                   1.686442e+07
FAKE                   2.000000e+00
RA                     4.115776e+01
DECL                  -2.720409e+01
PIXSIZE                2.700000e-01
                           ...
SIM_GALFRAC_r          1.987298e+00
SIM_GALFRAC_i          2.595640e+00
SIM_SUBSAMPLE_INDEX   -9.000000e+00
Unnamed: 82                     NaN
d                               NaN
Length: 79, dtype: float64

In [18]:
std(df)

SNID                   9.683684e+06
FAKE                   0.000000e+00
RA                     1.480021e+01
DECL                   1.505105e+01
PIXSIZE                2.646250e-13
                           ...
SIM_GALFRAC_r          6.478933e+00
SIM_GALFRAC_i          7.795332e+00
SIM_SUBSAMPLE_INDEX    0.000000e+00
Unnamed: 82                     NaN
d                               NaN
Length: 79, dtype: float64

The dataset has 82 columns*, which are specific to astronomical observations, particularly supernovae. Explanation of the most relevant columns based on general astronomy and supernovae terminology:

1. SUBSURVEY: Subsection of the main survey where the supernova was observed.(-)
2. SNID: Unique identifier for each supernova.(-)
3. IAUC: International Astronomical Union Circular number, used for identification.(-)
4. FAKE: Binary indicator, possibly showing if the supernova is simulated (e.g., 1 for real, 2 for simulated).(groupby or sortvalues)(datatype to integer)
5. RA (Right Ascension): Angular distance measured eastward along the celestial equator.(+)
6. DECL (Declination): Angular distance north or south of the celestial equator.(+)
7. PIXSIZE: Pixel size in arcseconds for the telescope’s images.(-)
8. NXPIX, NYPIX: Number of pixels in X and Y directions for the image.(-)
9. CCDNUM: CCD (Charge-Coupled Device) number capturing the image.(-)
10. SNTYPE: Type of the supernova (e.g., Type Ia, Ib/c, II).(groupby)
11. NOBS: Number of observations of the supernova.(+)
12. MWEBV: Milky Way extinction in E(B-V), accounting for light absorption by dust.(+)
13. REDSHIFT_HELIO / REDSHIFT_FINAL: Redshift values indicating how far the supernova is based on Doppler shift.(+)
14. HOSTGAL_PHOTOZ / HOSTGAL_PHOTOZ: Photometric and spectroscopic redshifts of the host galaxy.(+)
15. HOSTGAL_SNSEP: Separation distance between the supernova and its host galaxy.(+)
16. HOSTGAL_LOGMASS: Logarithmic stellar mass of the host galaxy.(+)
17. HOSTGAL_MAG_g/r/i/z: Apparent magnitudes of the host galaxy in different filters (g, r, i, z bands).(+)
18. PEAKMJD: Modified Julian Date of the supernova's peak brightness. (date)
19. SIM_MODEL_NAME / SIM_MODEL_INDEX: Name and index of the simulation model used (if simulated data).(-)
20. SIM_REDSHIFT_HELIO / CMB / HOST: Simulated redshifts in various reference frames.(-)
21. SIM_PEAKMAG_g/r/i/z: Simulated peak magnitudes of the supernova in g, r, i, and z filters.
22. SIM_EXPOSURE_g/r/i/z: Exposure time for each band (g, r, i, z).(+)
23. SIM_GALFRAC_g/r/i/z: Fraction of galaxy light contributing to the supernova brightness in each filter.(+)

- Redshift values determine the distance of the supernova, which helps identify its type and luminosity.
- Host galaxy properties such as mass, magnitude, and redshift are critical for understanding the environment of the supernova.
- SIM columns refer to simulated data and associated model parameters, helpful for machine learning tasks or comparisons.
- Magnitudes (MAG and PEAKMAG) are expressed in standard astronomical filters (g, r, i, z).

In [20]:
df.sample(10)

,SUBSURVEY,SNID,IAUC,FAKE,RA,DECL,PIXSIZE,NXPIX,NYPIX,CCDNUM,...,SIM_EXPOSURE_r,SIM_EXPOSURE_i,SIM_EXPOSURE_z,SIM_GALFRAC_g,SIM_GALFRAC_r,SIM_GALFRAC_i,SIM_GALFRAC_z,SIM_SUBSAMPLE_INDEX,Unnamed: 82,d
36694,,9518291.0,NULL,2.0,42.607941,0.672820,0.27,-9.0,-9.0,5.0,...,1.0,1.0,1.0,2.395751e+00,1.909392,2.706454,3.41406,-9.0,NaN,NaN
39899,,17614193.0,NULL,2.0,53.969121,-27.415672,0.27,-9.0,-9.0,41.0,...,1.0,1.0,1.0,1.390000e-14,0.531543,0.675254,1.028383,-9.0,NaN,NaN
12036,,20731636.0,NULL,2.0,41.027824,-0.380766,0.27,-9.0,-9.0,9.0,...,1.0,1.0,1.0,8.059197e-01,1.492480,3.081903,5.091919,-9.0,NaN,NaN
22486,,13868672.0,NULL,2.0,35.668786,-4.222281,0.27,-9.0,-9.0,13.0,...,1.0,1.0,1.0,1.010000e-13,13.468886,5.353993,5.47095,-9.0,NaN,NaN
24739,,29798482.0,NULL,2.0,36.529705,-3.979897,0.27,-9.0,-9.0,10.0,...,1.0,1.0,1.0,1.799467e+00,0.982479,1.878436,2.878982,-9.0,NaN,NaN
29109,,22583263.0,NULL,2.0,53.452454,-28.372356,0.27,-9.0,-9.0,44.0,...,1.0,1.0,1.0,1.621417e+00,9.213850,20.863678,35.970783,-9.0,NaN,NaN
15494,,31545096.0,NULL,2.0,53.410942,-28.705029,0.27,-9.0,-9.0,55.0,...,1.0,1.0,1.0,4.230000e-14,2.234250,1.999230,2.519294,-9.0,NaN,NaN
38439,,12638801.0,NULL,2.0,52.785609,-27.789080,0.27,-9.0,-9.0,22.0,...,1.0,1.0,1.0,3.720000e-14,2.344623,1.460585,2.287359,-9.0,NaN,NaN
15802,,23089934.0,NULL,2.0,36.810007,-5.576679,0.27,-9.0,-9.0,62.0,...,1.0,1.0,1.0,1.470000e-14,0.608106,0.643137,0.816273,-9.0,NaN,NaN
4537,,6313647.0,NULL,2.0,10.140286,-43.692829,0.27,-9.0,-9.0,23.0,...,1.0,1.0,1.0,5.663311e-01,0.238377,0.301450,0.49589893,-9.0,NaN,NaN

Columns we would need are

In [122]:
snova =df[['RA','DECL','CCDNUM','SNTYPE','NOBS','PTROBS_MIN','PTROBS_MAX','MWEBV','REDSHIFT_HELIO','REDSHIFT_FINAL','HOSTGAL_PHOTOZ','HOSTGAL_PHOTOZ','HOSTGAL_SNSEP','HOSTGAL_MAG_g','HOSTGAL_MAG_r','HOSTGAL_MAG_i','HOSTGAL_MAG_z','HOSTGAL_SB_FLUXCAL_g','HOSTGAL_SB_FLUXCAL_r','HOSTGAL_SB_FLUXCAL_i','HOSTGAL_SB_FLUXCAL_z','PEAKMJD']]

In [124]:
snova.describe()

,RA,DECL,CCDNUM,SNTYPE,NOBS,PTROBS_MIN,PTROBS_MAX,MWEBV,REDSHIFT_HELIO,REDSHIFT_FINAL,...,HOSTGAL_SNSEP,HOSTGAL_MAG_g,HOSTGAL_MAG_r,HOSTGAL_MAG_i,HOSTGAL_MAG_z,HOSTGAL_SB_FLUXCAL_g,HOSTGAL_SB_FLUXCAL_r,HOSTGAL_SB_FLUXCAL_i,HOSTGAL_SB_FLUXCAL_z,PEAKMJD
count,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.000000
mean,39.835341,-19.407487,31.58690,113.696525,59.514675,7.265142e+05,7.265727e+05,0.019503,0.575154,0.574195,...,0.903766,22.742349,21.716528,21.182901,20.885021,1.740688e+01,4.537166e+01,72.037788,96.410212,56970.734373
std,14.800212,15.051050,17.43592,12.265149,24.185423,4.221569e+05,4.221561e+05,0.014569,0.242783,0.242666,...,0.884224,1.526001,1.605334,1.506787,1.539659,3.205350e+01,7.450446e+01,112.071381,149.658415,295.004058
min,6.392980,-44.976723,1.00000,101.000000,5.000000,1.000000e+00,2.400000e+01,0.004443,0.034409,0.034032,...,0.011082,15.506805,14.603941,14.314263,13.882751,6.170000e-32,6.060000e-32,0.059021,0.346376,56532.600000
25%,35.716156,-28.640380,16.00000,101.000000,42.000000,3.643522e+05,3.643975e+05,0.008697,0.384356,0.383452,...,0.457397,21.979745,20.810130,20.291965,19.957708,4.697167e+00,1.116480e+01,18.761564,24.110729,56646.160000
50%,41.157764,-27.204088,32.00000,120.000000,60.000000,7.220920e+05,7.221555e+05,0.012529,0.551053,0.550117,...,0.734558,22.899212,21.952983,21.421996,21.109768,8.923329e+00,2.194780e+01,35.620203,47.380703,56968.081000
75%,52.866702,-4.633564,47.00000,122.000000,73.000000,1.082232e+06,1.082257e+06,0.026986,0.745504,0.744598,...,1.112136,23.684738,22.758463,22.198310,21.937036,1.730076e+01,4.849052e+01,78.526965,106.609803,57289.589000
max,55.512060,0.978050,62.00000,133.000000,223.000000,1.546222e+06,1.546249e+06,0.099128,1.418761,1.417786,...,38.944714,99.027360,99.030850,24.942570,25.424816,9.282989e+02,2.037194e+03,2805.568800,3898.577100,57414.984000

In [24]:
mean (snova)

RA                          39.835341
DECL                       -19.407487
CCDNUM                      31.586900
SNTYPE                     113.696525
NOBS                        59.514675
PTROBS_MIN              726514.197675
PTROBS_MAX              726572.712350
MWEBV                        0.019503
REDSHIFT_HELIO               0.575154
REDSHIFT_FINAL               0.574195
HOSTGAL_PHOTOZ               0.574021
HOSTGAL_PHOTOZ               0.574021
HOSTGAL_SNSEP                0.903766
HOSTGAL_MAG_g               22.742349
HOSTGAL_MAG_r               21.716528
HOSTGAL_MAG_i               21.182901
HOSTGAL_MAG_z               20.885021
HOSTGAL_SB_FLUXCAL_g        17.406883
HOSTGAL_SB_FLUXCAL_r        45.371664
HOSTGAL_SB_FLUXCAL_i        72.037788
HOSTGAL_SB_FLUXCAL_z        96.410212
PEAKMJD                  56970.734373
dtype: float64

Likewise by calling all the above functions we can get the Range,Mean,Median and Standard Deviation of the required dataset

In [26]:
simulation_data = df[['SIM_RA','SIM_DECL','SIM_MWEBV','SIM_MODEL_NAME','SIM_REDSHIFT_HELIO','SIM_REDSHIFT_CMB','SIM_REDSHIFT_HOST','SIM_PEAKMAG_g','SIM_PEAKMAG_r','SIM_PEAKMAG_i','SIM_PEAKMAG_z','SIM_GALFRAC_g','SIM_GALFRAC_r','SIM_GALFRAC_i','SIM_GALFRAC_z','SIM_PEAKMJD']]

In [27]:
mean (simulation_data)

SIM_RA                   39.835341
SIM_DECL                -19.407487
SIM_MWEBV                 0.019437
SIM_REDSHIFT_HELIO        0.585255
SIM_REDSHIFT_CMB          0.584290
SIM_REDSHIFT_HOST         0.583485
SIM_PEAKMAG_g            12.593981
SIM_PEAKMAG_r            23.655434
SIM_PEAKMAG_i            23.395602
SIM_PEAKMAG_z            22.711626
SIM_GALFRAC_g            10.193549
SIM_GALFRAC_r             3.732287
SIM_GALFRAC_i             4.883576
SIM_PEAKMJD           56970.726358
dtype: float64

Likewise

b.Does the dataset require normalization?

To find if the given dataset requires we need to analyse the data and for that we need to analyse the data

In [126]:
snova = snova.sort_values('PEAKMJD')

In [130]:
snova.iloc[0:40000]

,RA,DECL,CCDNUM,SNTYPE,NOBS,PTROBS_MIN,PTROBS_MAX,MWEBV,REDSHIFT_HELIO,REDSHIFT_FINAL,...,HOSTGAL_SNSEP,HOSTGAL_MAG_g,HOSTGAL_MAG_r,HOSTGAL_MAG_i,HOSTGAL_MAG_z,HOSTGAL_SB_FLUXCAL_g,HOSTGAL_SB_FLUXCAL_r,HOSTGAL_SB_FLUXCAL_i,HOSTGAL_SB_FLUXCAL_z,PEAKMJD
18960,7.964774,-43.058843,35.0,120.0,65.0,302702.0,302766.0,0.006489,0.325263,0.324282,...,1.628548,21.249779,19.928646,19.345495,18.953949,20.989200,70.867820,121.257690,173.911300,56532.600
19546,9.154964,-44.037899,34.0,120.0,64.0,300954.0,301017.0,0.006672,0.263732,0.262824,...,1.113105,22.961388,22.405537,22.215391,22.175000,7.706414,12.858574,15.319732,15.900393,56532.640
7067,8.926306,-44.143313,34.0,101.0,69.0,703837.0,703905.0,0.007498,0.429673,0.428646,...,0.857998,22.389002,21.476469,21.206387,20.951624,15.437870,35.776714,45.881104,58.014824,56532.723
28041,54.626771,-26.131331,3.0,101.0,14.0,128868.0,128881.0,0.012054,0.645906,0.645294,...,0.920953,23.871365,23.070963,22.605574,22.398827,3.912235,8.176843,12.552827,15.185893,56533.290
7324,34.246014,-4.689911,21.0,133.0,61.0,1450300.0,1450360.0,0.018959,0.276122,0.275058,...,0.678824,20.464855,19.465430,18.988567,18.776438,70.921364,178.052440,276.243900,335.849000,56533.310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3542,54.682084,-28.833479,22.0,120.0,16.0,142162.0,142177.0,0.012033,0.269749,0.269300,...,1.449941,20.510590,19.562004,19.137728,18.893827,47.629353,114.106070,168.662800,211.144360,57413.620
21156,36.243108,-6.169584,23.0,101.0,9.0,67982.0,67990.0,0.033524,0.251427,0.250430,...,3.087136,18.947433,18.017294,17.575567,17.290945,27.397713,64.531204,96.930470,125.982280,57414.312
32696,40.827876,-1.825558,60.0,101.0,13.0,738867.0,738879.0,0.028452,0.352052,0.351056,...,1.334764,20.608957,19.587507,19.189300,18.859129,45.404266,116.326020,167.864800,227.524440,57414.400
10000,52.179695,-28.188521,34.0,120.0,16.0,347204.0,347219.0,0.006970,0.167375,0.166908,...,1.590363,17.804937,16.830480,16.396576,16.055010,225.724520,553.810300,825.891240,1131.227200,57414.500
39998,53.313236,-27.079382,25.0,101.0,7.0,253404.0,253410.0,0.009418,0.070448,0.070032,...,1.359578,20.636421,20.366995,20.262226,20.207468,27.807230,35.639256,39.249650,41.279903,57414.984

In [132]:
snova.describe()

,RA,DECL,CCDNUM,SNTYPE,NOBS,PTROBS_MIN,PTROBS_MAX,MWEBV,REDSHIFT_HELIO,REDSHIFT_FINAL,...,HOSTGAL_SNSEP,HOSTGAL_MAG_g,HOSTGAL_MAG_r,HOSTGAL_MAG_i,HOSTGAL_MAG_z,HOSTGAL_SB_FLUXCAL_g,HOSTGAL_SB_FLUXCAL_r,HOSTGAL_SB_FLUXCAL_i,HOSTGAL_SB_FLUXCAL_z,PEAKMJD
count,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.000000
mean,39.835341,-19.407487,31.58690,113.696525,59.514675,7.265142e+05,7.265727e+05,0.019503,0.575154,0.574195,...,0.903766,22.742349,21.716528,21.182901,20.885021,1.740688e+01,4.537166e+01,72.037788,96.410212,56970.734373
std,14.800212,15.051050,17.43592,12.265149,24.185423,4.221569e+05,4.221561e+05,0.014569,0.242783,0.242666,...,0.884224,1.526001,1.605334,1.506787,1.539659,3.205350e+01,7.450446e+01,112.071381,149.658415,295.004058
min,6.392980,-44.976723,1.00000,101.000000,5.000000,1.000000e+00,2.400000e+01,0.004443,0.034409,0.034032,...,0.011082,15.506805,14.603941,14.314263,13.882751,6.170000e-32,6.060000e-32,0.059021,0.346376,56532.600000
25%,35.716156,-28.640380,16.00000,101.000000,42.000000,3.643522e+05,3.643975e+05,0.008697,0.384356,0.383452,...,0.457397,21.979745,20.810130,20.291965,19.957708,4.697167e+00,1.116480e+01,18.761564,24.110729,56646.160000
50%,41.157764,-27.204088,32.00000,120.000000,60.000000,7.220920e+05,7.221555e+05,0.012529,0.551053,0.550117,...,0.734558,22.899212,21.952983,21.421996,21.109768,8.923329e+00,2.194780e+01,35.620203,47.380703,56968.081000
75%,52.866702,-4.633564,47.00000,122.000000,73.000000,1.082232e+06,1.082257e+06,0.026986,0.745504,0.744598,...,1.112136,23.684738,22.758463,22.198310,21.937036,1.730076e+01,4.849052e+01,78.526965,106.609803,57289.589000
max,55.512060,0.978050,62.00000,133.000000,223.000000,1.546222e+06,1.546249e+06,0.099128,1.418761,1.417786,...,38.944714,99.027360,99.030850,24.942570,25.424816,9.282989e+02,2.037194e+03,2805.568800,3898.577100,57414.984000

We have found missing values and since its only 3 rows we are dropping them since almost all values of those rows are missing and such missing rows could affect the running of a ML algorithm

Yes the dataset definitely needs to be scaled so that the many distributions could be compared easily. Normalization is an important in preparing data for machine learning. The goal would be to change values in datasets to a common scale without distorting differences in ranges of values or losing info. Just look at the ranges of the values theyre very different from each other and so comparison is almost impossible if not for normalization

In [134]:
import seaborn as sns